version: '2.3'

services:
  plex:
    image: rtsundland/plex
    build: ./plex
    hostname: plex
    container_name: plex
    restart: unless-stopped
    env_file: ./misc/env
    network_mode: host
#     internal:
#        ipv4_address: 10.0.1.30

    volumes:
      - plex_config:/config
      - plex_library:/media
      - plex_backup:/backup

    ports:
      -  32400/tcp
      -  32400/udp
      -  32469/tcp
      -  32469/udp
      -  5353/udp
      -  1900/udp

#
# To enable NVIDIA transcoding, uncomment
#    runtime: nvidia

#
# To enable Intel QuickSync transcoding, uncomment
#    devices:
#      - /dev/dri

volumes:
  plex_config:
    external: true

  plex_library:
    external: true

  plex_backup:
    external: true

