version: '2.3'

services:
  plex:
    image: rtsundland/plex
    build: ./plex
    hostname: plex
    container_name: plex
    restart: unless-stopped
    env_file: ./misc/env
    networks:
      internal:
        ipv4_address: 10.0.1.30

    volumes:
      - plex_config:/config
      - plex_library:/media
      - plex_backup:/backup

#
# To enable NVIDIA transcoding, uncomment
#    runtime: nvidia

#
# To enable Intel QuickSync transcoding, uncomment
#    devices:
#      - /dev/dri

volumes:
  plex_config:
    external: true

  plex_library:
    external: true

  plex_backup:
    external: true

networks:
  internal:
    name: internal
    driver: macvlan
    driver_opts:
      parent: enp0s4
    ipam:
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1

